---
title: "Portfolio"
output: html_document
---

```{r setup, results="hide", warning=FALSE, message=FALSE}
setwd("~/Documents/University of Waterloo/Fourth Year/4B/INTEG375")
library(foreign)
library(ggplot2)

sleep <- read.csv("SleepDataPortfolio.csv" , header=T, sep=",")

#Bar Graph of Sleeping Habits
ggplot(data=sleep, aes(x=Date, y=Hours.Slept)) + 
    geom_bar(stat = "identity", position="dodge") +
    theme_minimal() +
    theme(axis.text.x=element_text(angle=90, size=8))  

#Line Graph
ggplot(sleep, aes(x=Date, y=Hours.Slept, group=1)) + 
      geom_line() +
      theme_minimal() +
      theme(axis.text.x=element_text(angle=90, size=8))  


#Hours Slept over Sleep Rating
ggplot(sleep, aes(Date, group=2)) + 
  geom_line(aes(y = Hours.Slept, colour = "Hours.Slept")) + 
  geom_line(aes(y = RestRating, colour = "Rest.Rating")) +
  theme_minimal() +
  theme(axis.text.x=element_text(angle=90, size=8))  
#need to reverse order of date(x axis)


#Rest rating over steps per day
ggplot(sleep, aes(Date, group=2)) + 
  geom_line(aes(y = StepsPerDay, colour = "Steps")) + 
  geom_line(aes(y = RestRating, colour = "Rest.Rating")) +
  theme_minimal() +
  theme(axis.text.x=element_text(angle=90, size=8)) 
#need to reverse order of date(x axis)
#change these both to percent, for steps..100%=10000 steps, for sleep, 100%=8 hours
